### ISSUE TITLE
FYI - sc2-sdk import issue

### ISSUE THREAD

**Issue by sarhugo** [mktcode/vue-steemconnect#1]
I was using your package but sc2-sdk was causing me problems while importing. Check issue https://github.com/steemit/steemconnect-sdk/issues/50

Now I had to make a local fork of your lib so I can work with the new beta version (import statement must be changed).

Once sc2-sdk releases the 2.0 stable version I guess you will have to check for this change

Regards

**Comment by mktcode** [comment]
Thanks. We're already trying to solve this.
